spring:
  application:
    name: Retroden

  datasource:
    url: jdbc:postgresql://localhost:5432/retroden
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

  management:
    endpoints:
      web:
        exposure:
          include: [ "prometheus" ]